name: photoid
description: 智能证件照 - 本地处理的合规证件照
publish_to: 'none'
version: 0.3.4+16

environment:
  sdk: ^3.5.0

dependencies:
  camera: ^0.12.1
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_localizations:
    sdk: flutter
  gal: ^2.3.3
  google_mlkit_face_detection: ^0.15.1
  google_mlkit_selfie_segmentation: ^0.12.1
  http: ^1.6.0
  image: ^4.9.2
  image_picker: ^1.2.3
  intl: ^0.20.3
  onnxruntime: ^1.4.1
  open_filex: ^4.7.0
  package_info_plus: ^10.2.1
  path: ^1.9.1
  path_provider: ^2.1.6
  permission_handler: ^13.0.2
  shared_preferences: ^2.5.5
  vector_math: ^2.4.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/photo_specs.json
    - assets/icon.png
    - assets/models/hivision_modnet.onnx

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  adaptive_icon_background: "#2B6CB0"
  adaptive_icon_foreground: "assets/icon.png"
  remove_alpha_ios: true
